
# implementazione precedente (disponibilità source in scadenza? il sito argentovivo si basa sui vecchi identificativi)
1.dataset=fotografie storiche
1.splitter=,
1.split=ip_it,CP_it_syn,TK_it,B1p_url
1.xslt=fotografia.v1.xslt
#1.2rdf.xslt=fotografia2rdf.xslt
1.rdfizer.xslt=fotografia2rdf.v1.xslt
# ? see RdfAltoAdige.java (assume inventari con prefisso lav univoci nella definizione dell'uri)
1.itemId=row/cell[@name='priref']
1.date=row/cell[@name='modification']
1.documentPrefix=https://www.lichtbild-argentovivo.eu/it/banca-dati-fotografica/ricerca-immagini.html?detail=
1.filterCell=MUS
1.filterList=tap
1.class=CsvRow2domReader
#1.csv=http://daten.buergernetz.bz.it/services/kksSearch/collect/lichtbild?q=*:*&fl=*&rows=999999&wt=csv
# filtro schede con immagine
1.source=http://daten.buergernetz.bz.it/services/kksSearch/collect/lichtbild?q=B1p_url:*&fl=*&rows=999999&wt=csv
# test
#1.csv=file:./source/lichtbild.csv
#1.csv=file:./source/testfs.csv

# nuova implementazione ma interfaccia catalogo
#1.dataset=fotografie storiche
#1.xslt=fotografia.xslt
#1.rdfizer.xslt=fotografia2rdf.xslt
# ? see RdfAltoAdige.java
#1.itemId=row/cell[@name='priref']
#1.date=row/cell[@name='modification']
##1.documentPrefix=https://www.lichtbild-argentovivo.eu/it/banca-dati-fotografica/ricerca-immagini.html?detail=
#1.documentPrefix=https://oggetti-musei-archivi.provincia.bz.it/Details/bz/
#1.filterCell=MUS
#1.filterList=tap
#1.class=XPager
#1.source.xslt=filter.xslt
#1.source.element=record
#1.source.page=256
## con il filtro su collection.name restituisce sol "brieffields"
#1.source=https://api.integrations.services.siag.it/objmusarcOpenData/search?database=bz&search=priref=*+and+collection.name=*Lichtbild?Interreg?V*

# catalogo
2.dataset=beni culturali
# TODO il valore è nel codice ma la dichiarazione lo attiva
#2.splitter=,
#2.split=ip_it,CP_it_syn,TK_it,B1p_url
2.xslt=fotografia.xslt
#2.2rdf.xslt=fotografia2rdf.xslt
2.rdfizer.xslt=fotografia2rdf.xslt
# ? see RdfAltoAdige.java
2.itemId=row/cell[@name='priref']
#2.date=row/cell[@name='modification']
#2.dateDocument=https://data.civis.bz.it/it/dataset/objects-museums-archives/resource/71f6c1c4-403e-4c0e-8f40-044a34039cc0
# TODO (double match) 2.datePattern=last_modified.*</td;[0-9][^<]*
# *** data modifica non disponibile - last_modified =>	None 
#2.documentPrefix=https://www.provincia.bz.it/catalogo-beniculturali/it/ricerca-detaglio.asp?kks_priref=
#2.documentPrefix=https://oggetti-musei-archivi.provincia.bz.it/search/simple$(NOTHING)
2.documentPrefix=https://oggetti-musei-archivi.provincia.bz.it/Details/bz/
#2.charset=UTF-8
#2.filterCell=OB_it
#2.filterList=cartolina illustrata,cartolina postale,diapositiva,diapositive,fotografia,negativo
2.filterCell=MUS
2.filterList=tap
#2.csv=http://dati.retecivica.bz.it/services/kksSearch/collect/select?q=*:*&fl=*&rows=999999&wt=csv
# filtro schede con immagine e oggetto
##2.csv=http://dati.retecivica.bz.it/services/kksSearch/collect/select?q=B1p_url:*&fl=*&rows=999999&wt=csv
2.class=XPager
2.source.xslt=filter.xslt
2.source.element=record
2.source.page=256
#2.source=http://dati.retecivica.bz.it/services/kksSearch/collect/select?q=(B1p_url:*)%20AND%20(OB_it:*)&fl=*&rows=999999&wt=csv
#2.source=https://api.integrations.services.siag.it/objmusarcOpenData/search?database=bz&search=priref=120065618&fields=historical_critical_notes,dimension.unit,dating.date.end,description,creator.role,institution.code,media.reference,object_number,creator,content.geographical_keyword.gis,content.geographical_keyword,dimension.part,collection.name,dating.date.end.prec,technique,dating.date.start,content.person.name,content.organisation,content.geographical_keyword.gis_exact,material,dimension.value,dimension.type,title,content.subject.type,object_name,dating.date.start.prec,dimension.precision,content.subject
#2.source=https://api.integrations.services.siag.it/objmusarcOpenData/search?database=bz&search=priref=*&fields=historical_critical_notes,dimension.unit,dating.date.end,description,creator.role,institution.code,media.reference,object_number,creator,content.geographical_keyword.gis,content.geographical_keyword,dimension.part,collection.name,dating.date.end.prec,technique,dating.date.start,content.person.name,content.organisation,content.geographical_keyword.gis_exact,material,dimension.value,dimension.type,title,content.subject.type,object_name,dating.date.start.prec,dimension.precision,content.subject&limit=256&startFrom=43008
2.source=https://api.integrations.services.siag.it/objmusarcOpenData/search?database=bz&search=priref=*&fields=historical_critical_notes,dimension.unit,dating.date.end,description,creator.role,institution.code,media.reference,object_number,creator,content.geographical_keyword.gis,content.geographical_keyword,dimension.part,collection.name,dating.date.end.prec,technique,dating.date.start,content.person.name,content.organisation,content.geographical_keyword.gis_exact,material,dimension.value,dimension.type,title,content.subject.type,object_name,dating.date.start.prec,dimension.precision,content.subject&limit=256&startFrom=

# la nuova implementazione legge i dati base da institution replicato in tutte le schede (la prima di una selezione basata sull'identificativo del museo institution.code)
#  integrando con quanto pubblicato sul dataset json dedicato se trova la corrispondenza institution.code <=> map[@key='elements']/map[@key='mus']/string[@key='value']
3.dataset=CF CG
3.xslt=CG_Musei_AltoAdige.xslt,CF_Musei_AltoAdige.xslt
#3.rdfizer.xslt=CF_CG_de.xslt
3.rdfizer.xslt=CF_CG_de_musei.xslt
3.idprefix=AA_CG_,AA_CF_
3.cgmap=true,false
3.cfmap=false,true
3.itemId=row/cell[@name='MUS']
#3.date=row/cell[@name='modification']
#3.dateDocument=https://data.civis.bz.it/it/dataset/musei-in-alto-adige/resource/6147982c-bb44-445b-bda0-3f090f589b2c
# TODO (double match) 3.datePattern=last_modified.*</td;[0-9][^<]*
3.itemDenom=row/cell[@name='BEZEICHNUNG_I']
3.documentPrefix=

3.class=XPager
3.source.xslt=filterMUS.xslt
3.source.element=record
3.source.page=ALD,AUG,BAL,BRU,BVI,DBX,EKM,FRH,FRM,FSC,GUF,GVA,KLA,KMA,LAV,LFB,LMB,LUM,LVA,MAL,MAR,MGH,MHP,MSK,MUR,MVB,MZK,MZM,NMS,NUS,OSW,PAS,PMB,PNO,ROH,SAB,SAM,SBM,SGB,SJF,SKM,SLA,SME,SML,SMM,SOM,SSP,STM,SVM,SWM,TAP,TEI,TRA,TST,UTM,VCT,VEM,VIM,ZAV
#3.source=https://api.integrations.services.siag.it/objmusarcOpenData/search?database=bz&fields=institution.name&limit=1&search=institution.code=ALD
3.source=https://api.integrations.services.siag.it/objmusarcOpenData/search?database=bz&fields=institution.name&limit=1&search=institution.code=
3.source.xslt.urlparam.name=json
3.source.xslt.urlparam.source=https://api.integrations.services.siag.it/pub/cocweb/musport/opendata/api/items?system.type=museum&includeTotalCount=true

3.class=XPager

3.fieldmap=,NAME_IT|BEZEICHNUNG_I;NAME_DE|BEZEICHNUNG_D;CITY_IT|ORTSCHAFT_I;CITY_DE|ORTSCHAFT_D;POSTCODE|PLZ;ADDRESS_IT|ADRESSE_I;ADDRESS_DE|ADRESSE_D;EMAIL|EMAIL_I;PHONE|TELEFON;WEBSITE_IT|HOMEPAGE_I;WEBSITE_DE|HOMEPAGE_D
3.filterCode=mus

resourcePrefix=https://w3id.org/arco/resource/AltoAdige/
