
# architetture
# Architetture negli istituti culturali di Regione Lombardia
#   https://www.dati.lombardia.it/Cultura/Architetture-negli-istituti-culturali-di-Regione-L/d4mx-64y5/about_data
1.dataset=Architetture
#1.id=kf9b-rj2t
1.id=d4mx-64y5
1.splitter=;\u0020
1.split=DATAZIONE,AUTORI,USO_ATTUALE,USO_STORICO,STATO_CONSERV,STILE_SCUOLA
1.xslt=architettura.xslt
1.2rdf.xslt=architettura2rdf.xslt
1.itemId=row/cell[@name='NUM_SCHEDA_SIRBEC']
1.documentPrefix=https://www.lombardiabeniculturali.it/architetture/schede/

# reperti archeologici
# Reperti archeologici contenuti negli istituti culturali di Regione Lombardia
#   https://www.dati.lombardia.it/Cultura/Reperti-archeologici-contenuti-negli-istituti-cult/wv78-tdv2/about_data
2.dataset=Reperti Archeologici conservati nei Musei
#2.id=97ng-v559
2.id=wv78-tdv2
2.splitter=||
2.split=FUR,RSR,MTC,AUTN,AUTS,AUTA,ATBD,MISU,MISA,MISL,MISP,MISD,MISN
2.xslt=archeologia.xslt
2.2rdf.xslt=archeologia2rdf.xslt
2.itemId=row/cell[@name='IDK']
2.documentPrefix=https://www.lombardiabeniculturali.it/reperti-archeologici/schede/

# opere d'arte
# Opere d’Arte contenute negli istituti culturali di Regione Lombardia
#   https://www.dati.lombardia.it/Cultura/Opere-d-Arte-contenute-negli-istituti-culturali-di/ay8b-p38f/about_data
3.dataset=Opere d'Arte conservate nei Musei
#3.id=dsrv-9ish
3.id=ay8b-p38f
3.splitter=||
3.split=CMPN,FUR,MTC,RSR,SGTT,SGTI,AUTN,AUTS,AUTA,ATBD,ATBR,MISU,MISA,MISL,MISP,MISD,MISN,DTZG,DTZS,DTSI,DTSV,DTSF,DTSL
3.xslt=opera.xslt
3.2rdf.xslt=opera2rdf.xslt
3.itemId=row/cell[@name='IDK']
3.documentPrefix=https://www.lombardiabeniculturali.it/opere-arte/schede/
# nome della colonna con i valori da confrontare con filterList
#3.filterCell=TSK
# esclude tutte le righe con uno dei valori elencati (csv) nella cella
#3.filterList=OA
#3.filterList=D

# patrimonio scientifico tecnologico
# Patrimonio scientifico e tecnologico contenuti negli istituti culturali di Regione Lombardia
#   https://www.dati.lombardia.it/Cultura/Patrimonio-scientifico-e-tecnologico-contenuti-neg/ik6k-k4c4/about_data
4.dataset=Patrimonio Scientifico Tecnologico conservato nei Musei
#4.id=2k8u-uj4r
4.id=ik6k-k4c4
4.splitter=||
4.split=CTA,CTC,MTC,FUR,CMPN,RSR,STCC,STCD,MISU,MISA,MISL,MISP,MISD,MISN,AUTN,AUTS,AUTA,ATBD,ATBR,DTZG,DTZS,DTSI,DTSV,DTSF,DTSL,SGTI,COLD
4.xslt=tecnologico.xslt
4.2rdf.xslt=tecnologico2rdf.xslt
4.itemId=row/cell[@name='IDK']
4.documentPrefix=https://www.lombardiabeniculturali.it/scienza-tecnologia/schede/

# Beni etnoantropologici contenuti negli istituti culturali di Regione Lombardia
# https://www.dati.lombardia.it/Cultura/Beni-etnoantropologici-contenute-negli-istituti-cu/rsiy-z9u6/about_data
5.dataset=Beni Etnoantropologici conservati nei Musei
5.id=rsiy-z9u6
5.splitter=||
5.split=MTC,MISU,MISA,MISL,MISP,MISD,MISN,AGGD,AGGN,AUFN,AUFA,ATBT,ATBD,FUR
5.xslt=etnoantropologico.xslt
5.2rdf.xslt=etnoantropologico2rdf.xslt
5.itemId=row/cell[@name='IDK']
5.documentPrefix=https://www.lombardiabeniculturali.it/etnoantropologici/schede/

# Beni numismatici contenuti negli istituti culturali di Regione Lombardia
# https://www.dati.lombardia.it/Cultura/Beni-numismatici-contenuti-negli-istituti-cultural/8qzg-7d93/about_data
6.dataset=Beni Numismatici conservati nei Musei
6.id=8qzg-7d93
6.splitter=||
6.split=MTC,MISU,MISA,MISL,MISD,MISN,AUTN,AUTA,AUTS,DESN,DESF,DESR,DEST,DESU,AUEE,AUES,AUEZ,ZEC
6.xslt=numismatico.xslt
6.2rdf.xslt=numismatico2rdf.xslt
6.itemId=row/cell[@name='IDK']
6.documentPrefix=https://www.lombardiabeniculturali.it/numismatici/schede/

# Fotografie negli istituti culturali di Regione Lombardia
# https://www.dati.lombardia.it/Cultura/Fotografie-negli-istituti-culturali-di-Regione-Lom/ir82-62ur/about_data
7.dataset=Beni fotografici conservati nei Musei
7.id=ir82-62ur
7.splitter=||
7.split=SGTI,AUFN,AUFA,AUFS,ATBD,MISO,MISU,MISA,MISL,MISD,RSR,FUR
7.xslt=fotografico.xslt
7.2rdf.xslt=fotografico2rdf.xslt
7.itemId=row/cell[@name='IDK']
7.documentPrefix=https://www.lombardiabeniculturali.it/fotografici/schede/

#Stampe e matrici d'incisione contenute negli istituti culturali di Regione Lombardia
#  https://www.dati.lombardia.it/Cultura/Stampe-e-matrici-d-incisione-contenute-negli-istit/t2sn-mp27/about_data
8.dataset=Stampe e matrici d'incisione conservate nei Musei
8.id=t2sn-mp27
8.splitter=||
8.split=DTZG,DTZS,DTSI,DTSV,DTSF,DTSL,AUTN,AUTA,AUTS,ATBD,ATBR,MTC,RSR,FUR
8.xslt=stampa.xslt
8.2rdf.xslt=stampa2rdf.xslt
8.itemId=row/cell[@name='IDK']
8.documentPrefix=https://www.lombardiabeniculturali.it/stampe-matrici/schede/

#Stampe e matrici d’incisione contenute negli istituti culturali di Regione Lombardia
#  https://www.dati.lombardia.it/Cultura/Stampe-e-matrici-d-incisione-contenute-negli-istit/t2sn-mp27/abou
#

# l'ordine delle righe non è deterministico
csv=https://www.dati.lombardia.it/api/views/$(id)/rows.csv?accessType=DOWNLOAD
#csv=file:./src/test/Opere.csv
# test
#csv=file:./source/$(id).csv
# eg: "21/7/20"
dateDocument=https://www.dati.lombardia.it/api/views.xml?method=getByResourceName&name=$(id)
datePath=/view/metadata/custom_fields/Frequenza-di-aggiornamento/@Data-ultima-modifica

resourcePrefix=https://w3id.org/arco/resource/Lombardia/

rmDup=row/cell[@name='NCTN']
rmRange=00727634<=>03227633
